### ISSUE TITLE
Project with presenter but no tasks disappears from My Projects view

### ISSUE THREAD

**Issue by gbrauen** [PyBossa/pybossa#1203]
Running PyBossa on a local server for an undergrad course.

I created a new project and verified that it was visible as a draft project for the user account that had just added it.  I then added a task presenter.  The project became invisible in the web interface unless I signed in with an admin account and looked in the admin dashboard or directly visited the project using: 
`http://<myserver>/project/<myproject>`

I could not see the project in the My Projects list under the account of the user that had just created the project.

If instead, I create the project, then import tasks, the project remains visible as a draft project until the task presenter is added.  Then it becomes published.

**Comment by alejandrodob** [comment]
Hello @gbrauen,

That is a known issue that is fixed in the latest versions of PyBossa. Can you try to [update](http://docs.pybossa.com/en/latest/install.html#updating-pybossa) your PyBossa server and check again? It should be fixed.

**Comment by gbrauen** [comment]
Hi @alejandrodob,

Thank you for the quick response.  I upgraded my server and I am now able to add a task presenter to a project with no tasks defined and still see the draft project in my list.

I am seeing a new issue with the upgrade but I'll check to see if that is already tracked by separate issue.
